"0","ggplot(iris_for_ggplot, aes(fill=observation) )"
"1","[1m[33mError[39m in `fortify()`:[22m
[38;5;232m[33m![38;5;232m `data` must be a [34m<data.frame>[38;5;232m, or an object coercible by `fortify()`, or a valid
  [34m<data.frame>[38;5;232m-like object coercible by `as.data.frame()`.[39m
[1mCaused by error in `.prevalidate_data_frame_like_object()`:[22m
[38;5;232m[33m![38;5;232m `dim(data)` must return an [34m<integer>[38;5;232m of length 2.[39m
Backtrace:
[90m  1. [39mggplot2::ggplot(iris_for_ggplot, aes(fill = observation))
[90m  2. [39mggplot2:::ggplot.default(iris_for_ggplot, aes(fill = observation))
[90m  4. [39m[1m[94mggplot2:::fortify.default([39m[22mdata, ...[1m[94m)[39m[22m
[90m 11. [39mggplot2:::validate_as_data_frame(model)
[90m 12. [39m[1m[94mggplot2:::.prevalidate_data_frame_like_object([39m[22mdata[1m[94m)[39m[22m
"
